# Generated by Django 3.1.1 on 2020-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer_review',
            name='prediction_review',
            field=models.IntegerField(default=0),
        ),
    ]
