# Generated by Django 3.1.2 on 2020-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_auto_20201005_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_review',
            name='token',
            field=models.CharField(default='7936104b73f9f19b7c1095ca6d3cbf673a57fbe6', max_length=100),
        ),
        migrations.AddField(
            model_name='new_york',
            name='token',
            field=models.CharField(default='7936104b73f9f19b7c1095ca6d3cbf673a57fbe6', max_length=100),
        ),
    ]
